feature/MWB-502
meaningfy-ws/mapping-workbench pull request #146
Opened 2024-05-19 09:04 UTC by SilverBerserk

2024-05-19 09:05 UTC, kaleanych approved these changes

2024-05-19 14:17 UTC, duprijil commented
![image](https://github.com/meaningfy-ws/mapping-workbench/assets/29858835/545e3c5b-86ad-4636-b6f0-64ea620c5e80)
Please update the buttons so they are white when you can press them. (Like buttons on middle)

2024-05-19 14:18 UTC, duprijil requested changes
See previous comment

2024-05-20 08:05 UTC, duprijil approved these changes
Nice

2024-05-20 08:05 UTC, merged