feature/MWB-550
meaningfy-ws/mapping-workbench pull request #152
Opened 2024-05-23 07:12 UTC by SilverBerserk

2024-05-23 07:12 UTC, kaleanych approved these changes

2024-05-24 09:19 UTC, duprijil requested changes
See comments

2024-05-24 09:19 UTC, duprijil commented on mapping_workbench/frontend/src/layouts/app/time-switch/time-switch.js
> +    console.log(localTimeZoneAbbr, moment.tz('America/Toronto').format('z'))
If this log is for testing, delete it

2024-05-24 09:19 UTC, duprijil commented on mapping_workbench/frontend/src/layouts/app/time-switch/time-switch.js
>      const timeZoneItems = ['Europe/Luxembourg', localTimeZone]
According to requirements, we decided to gave UTC (instead of Luxemburg) and local time. Please put instead of Luxemburg just UTC.

2024-05-28 08:33 UTC, duprijil requested changes

2024-05-28 08:33 UTC, duprijil commented on mapping_workbench/frontend/src/layouts/app/time-switch/time-switch.js
> +        return `UTC ${timeZone > 0 && '+'}${timeZone/60}`
As in the previous comments and requirements: We need UTC (just UTC) time as default and local time (here works good)
![image](https://github.com/meaningfy-ws/mapping-workbench/assets/29858835/1db135e9-b859-41f3-bf58-863d2ae777a0)

2024-05-31 13:08 UTC, duprijil approved these changes

2024-05-31 13:08 UTC, merged