Feature/mwb 164
meaningfy-ws/mapping-workbench pull request #38
Opened 2023-11-17 11:46 UTC by duprijil

2023-11-17 11:57 UTC, CaptainOfHacks commented on tests/unit/backend/sparql_test_suite/test_sparql_validation.py
> +    assert result_test_data.sparql_validation_result is not None
add test to check validation result content

2023-11-17 12:00 UTC, CaptainOfHacks commented on tests/unit/backend/shacl_test_suite/test_shacl_validation.py
>      assert shacl_validator.validate(None) is not None
add tests to check validation results content

2023-11-17 12:02 UTC, CaptainOfHacks requested changes
Looks good, improve tests to cover validation results content, check concrete content.

2023-11-17 13:23 UTC, duprijil commented on tests/unit/backend/shacl_test_suite/test_shacl_validation.py
>      assert shacl_validator.validate(None) is not None
done

2023-11-17 13:24 UTC, duprijil commented on tests/unit/backend/sparql_test_suite/test_sparql_validation.py
> +        assert result_test_data.sparql_validation_result is not None
done

2023-11-17 13:24 UTC, duprijil commented on tests/unit/backend/sparql_test_suite/test_sparql_validation.py
> +    assert result_test_data.sparql_validation_result is not None
done

2023-11-17 17:41 UTC, kaleanych approved these changes

2023-11-19 12:21 UTC, CaptainOfHacks approved these changes

2023-11-19 13:19 UTC, merged